- name: Setup and run Docker containers
  hosts: localhost
  tasks:
    # - name: Create Docker networks
    #   command: docker network create --subnet=172.28.0.0/16 mynetwork
    #   ignore_errors: yes

    # - name: Create second Docker network
    #   command: docker network create --subnet=172.29.0.0/16 mysecondnetwork
    #   ignore_errors: yes

    - name: Build target container image
      command: docker build -t target_container ./docker/target
      args:
        chdir: "{{ playbook_dir }}/.."

    - name: Build ping server container image
      command: docker build -t ping_server ./docker/attacker
      args:
        chdir: "{{ playbook_dir }}/.."

    - name: Run target server container
      command: docker run -d --name target_container --network mysecondnetwork --ip 172.29.0.2 target_container
      ignore_errors: yes

    - name: Run ping server container
      command: docker run -d --name ping_server --network mynetwork --ip 172.28.0.2 ping_server
      ignore_errors: yes

    - name: Show logs from ping server
      command: docker logs ping_server
