# vars.yml

containers:
  - id: 1
    mynetwork_ip: "172.28.0.10"
    mysecondnetwork_ip: "172.29.0.10"
    ssh_port: 2222
  - id: 2
    mynetwork_ip: "172.28.0.11"
    mysecondnetwork_ip: "172.29.0.11"
    ssh_port: 2223
  - id: 3
    mynetwork_ip: "172.28.0.12"
    mysecondnetwork_ip: "172.29.0.12"
    ssh_port: 2224
  - id: 4
    mynetwork_ip: "172.28.0.13"
    mysecondnetwork_ip: "172.29.0.13"
    ssh_port: 2225
  - id: 5
    mynetwork_ip: "172.28.0.14"
    mysecondnetwork_ip: "172.29.0.14"
    ssh_port: 2226
